### ISSUE TITLE
Add some sort of tests / ci integration

### ISSUE THREAD

**Issue by andir** [cooperlees/peerme#31]
It would be great if we could utilize something like `travis-ci` for integration tests. That could be helpful when working on PRs (from your perspective).

I can provide a simple `.travis-ci.yml` and some simple tests.

**Comment by jpaussa** [comment]
I think this might be a dupe of #10 ?

**Comment by andir** [comment]
Oh yeah sorry.. I had a quick look and must have missed it.

**Comment by jpaussa** [comment]
> I can provide a simple .travis-ci.yml and some simple tests.

We'd love that, we don't have any experience with travis.
